// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("BUYERCONTACTType")]
    public class BuyerContact
    {
        [XmlElement("Buyercontactpoint")]
        public Text Buyercontactpoint { get; set; }
        [XmlElement("Buyercontacttelephonenumber")]
        public Text Buyercontacttelephonenumber { get; set; }
        [XmlElement("Buyercontactemailaddress")]
        public Text Buyercontactemailaddress { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public BuyerContact()
        {
            Buyercontactemailaddress = new Text();
            Buyercontacttelephonenumber = new Text();
            Buyercontactpoint = new Text();
        }
    }
}