// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("BUYERPOSTALADDRESSType")]
    public class BuyerPostalAddress
    {
        [XmlElement("Buyeraddressline1")]
        public Text BuyerAddressline1 { get; set; }
        [XmlElement("Buyeraddressline2")]
        public Text BuyerAddressline2 { get; set; }
        [XmlElement("Buyeraddressline3")]
        public Text BuyerAddressline3 { get; set; }
        [XmlElement("Buyercity")]
        public Text BuyerCity { get; set; }
        [XmlElement("Buyerpostcode")]
        public Text BuyerPostCode { get; set; }
        [XmlElement("Buyercountrysubdivision")]
        public Text BuyerCountrySubdivision { get; set; }
        [XmlElement("Buyercountrycode")]
        public Code BuyerCountryCode { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public BuyerPostalAddress()
        {
            BuyerCountryCode = new Code();
            BuyerCountrySubdivision = new Text();
            BuyerPostCode = new Text();
            BuyerCity = new Text();
            BuyerAddressline3 = new Text();
            BuyerAddressline2 = new Text();
            BuyerAddressline1 = new Text();
        }
    }
}