// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("BUYERType")]
    public class Buyer
    {
        [XmlElement("Buyername")]
        public Text BuyerName { get; set; }
        [XmlElement("Buyertradingname")]
        public Text BuyerTradingName { get; set; }
        [XmlElement("Buyeridentifier")]
        public Identifier BuyerIdentifier { get; set; }
        [XmlElement("Buyerlegalregistrationidentifier")]
        public Identifier BuyerLegalRegistrationIdentifier { get; set; }
        [XmlElement("BuyerVATidentifier")]
        public Identifier BuyerVATidentifier { get; set; }
        [XmlElement("Buyerelectronicaddress")]
        public Identifier BuyerElectronicAddress { get; set; }
        [XmlElement("BUYERPOSTALADDRESS")]
        public BuyerPostalAddress BuyerPostalAddress { get; set; }
        [XmlElement("BUYERCONTACT")]
        public BuyerContact BuyerContact { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public Buyer()
        {
            BuyerContact = new BuyerContact();
            BuyerPostalAddress = new BuyerPostalAddress();
            BuyerElectronicAddress = new Identifier();
            BuyerVATidentifier = new Identifier();
            BuyerLegalRegistrationIdentifier = new Identifier();
            BuyerIdentifier = new Identifier();
            BuyerTradingName = new Text();
            BuyerName = new Text();
        }
    }
}