// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("CREDITTRANSFERType")]
    public class CreditTransfer
    {
        [XmlElement("Paymentaccountidentifier")]
        public Identifier Paymentaccountidentifier { get; set; }
        [XmlElement("Paymentaccountname")]
        public Text Paymentaccountname { get; set; }
        [XmlElement("Paymentserviceprovideridentifier")]
        public Identifier Paymentserviceprovideridentifier { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public CreditTransfer()
        {
            Paymentserviceprovideridentifier = new Identifier();
            Paymentaccountname = new Text();
            Paymentaccountidentifier = new Identifier();
        }
    }
}