// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("DELIVERTOADDRESSType")]
    public class DeliverToAddress
    {
        [XmlElement("Delivertoaddressline1")]
        public Text DeliverToAddressline1 { get; set; }
        [XmlElement("Delivertoaddressline2")]
        public Text Delivertoaddressline2 { get; set; }
        [XmlElement("Delivertoaddressline3")]
        public Text Delivertoaddressline3 { get; set; }
        [XmlElement("Delivertocity")]
        public Text DeliverToCity { get; set; }
        [XmlElement("Delivertopostcode")]
        public Text DelivertoPostCode { get; set; }
        [XmlElement("Delivertocountrysubdivision")]
        public Text DelivertoCountrySubdivision { get; set; }
        [XmlElement("Delivertocountrycode")]
        public Code DelivertoCountryCode { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public DeliverToAddress()
        {
            DelivertoCountryCode = new Code();
            DelivertoCountrySubdivision = new Text();
            DelivertoPostCode = new Text();
            DeliverToCity = new Text();
            Delivertoaddressline3 = new Text();
            Delivertoaddressline2 = new Text();
            DeliverToAddressline1 = new Text();
        }
    }
}