// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("DIRECTDEBITType")]
    public class DirectDebit
    {
        [XmlElement("Mandatereferenceidentifier")]
        public Identifier Mandatereferenceidentifier { get; set; }
        [XmlElement("Bankassignedcreditoridentifier")]
        public Identifier Bankassignedcreditoridentifier { get; set; }
        [XmlElement("Debitedaccountidentifier")]
        public Identifier Debitedaccountidentifier { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public DirectDebit()
        {
            Debitedaccountidentifier = new Identifier();
            Bankassignedcreditoridentifier = new Identifier();
            Mandatereferenceidentifier = new Identifier();
        }
    }
}