// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("DOCUMENTLEVELALLOWANCESType")]
    public class DocumentLevelAllowances
    {
        [XmlElement("Documentlevelallowanceamount")]
        public Amount Documentlevelallowanceamount { get; set; }
        [XmlElement("Documentlevelallowancebaseamount")]
        public Amount Documentlevelallowancebaseamount { get; set; }
        [XmlElement("Documentlevelallowancepercentage")]
        public Percentage Documentlevelallowancepercentage { get; set; }
        [XmlElement("DocumentlevelallowanceVATcategorycode")]
        public Code DocumentlevelallowanceVATcategorycode { get; set; }
        [XmlElement("DocumentlevelallowanceVATrate")]
        public Percentage DocumentlevelallowanceVATrate { get; set; }
        [XmlElement("Documentlevelallowancereason")]
        public Text Documentlevelallowancereason { get; set; }
        [XmlElement("Documentlevelallowancereasoncode")]
        public Code Documentlevelallowancereasoncode { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public DocumentLevelAllowances()
        {
            Documentlevelallowancereasoncode = new Code();
            Documentlevelallowancereason = new Text();
            DocumentlevelallowanceVATrate = new Percentage();
            DocumentlevelallowanceVATcategorycode = new Code();
            Documentlevelallowancepercentage = new Percentage();
            Documentlevelallowancebaseamount = new Amount();
            Documentlevelallowanceamount = new Amount();
        }
    }
}