// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("DOCUMENTLEVELCHARGESType")]
    public class DocumentLevelCharges
    {
        [XmlElement("Documentlevelchargeamount")]
        public Amount Documentlevelchargeamount { get; set; }
        [XmlElement("Documentlevelchargebaseamount")]
        public Amount Documentlevelchargebaseamount { get; set; }
        [XmlElement("Documentlevelchargepercentage")]
        public Percentage Documentlevelchargepercentage { get; set; }
        [XmlElement("DocumentlevelchargeVATcategorycode")]
        public Code DocumentlevelchargeVATcategorycode { get; set; }
        [XmlElement("DocumentlevelchargeVATrate")]
        public Percentage DocumentlevelchargeVATrate { get; set; }
        [XmlElement("Documentlevelchargereason")]
        public Text Documentlevelchargereason { get; set; }
        [XmlElement("Documentlevelchargereasoncode")]
        public Code Documentlevelchargereasoncode { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public DocumentLevelCharges()
        {
            Documentlevelchargereasoncode = new Code();
            Documentlevelchargereason = new Text();
            DocumentlevelchargeVATrate = new Percentage();
            DocumentlevelchargeVATcategorycode = new Code();
            Documentlevelchargepercentage = new Percentage();
            Documentlevelchargebaseamount = new Amount();
            Documentlevelchargeamount = new Amount();
        }
    }
}