// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("DOCUMENTTOTALSType")]
    public class DocumentTotals
    {
        [XmlElement("SumofInvoicelinenetamount")]
        public Amount SumofInvoicelinenetamount { get; set; }
        [XmlElement("Sumofallowancesondocumentlevel")]
        public Amount Sumofallowancesondocumentlevel { get; set; }
        [XmlElement("Sumofchargesondocumentlevel")]
        public Amount Sumofchargesondocumentlevel { get; set; }
        [XmlElement("InvoicetotalamountwithoutVAT")]
        public Amount InvoicetotalamountwithoutVAT { get; set; }
        [XmlElement("InvoicetotalVATamount")]
        public Amount InvoicetotalVATamount { get; set; }
        [XmlElement("InvoicetotalVATamountinaccountingcurrency")]
        public Amount InvoicetotalVATamountinaccountingcurrency { get; set; }
        [XmlElement("InvoicetotalamountwithVAT")]
        public Amount InvoicetotalamountwithVAT { get; set; }
        [XmlElement("Paidamount")]
        public Amount Paidamount { get; set; }
        [XmlElement("Roundingamount")]
        public Amount Roundingamount { get; set; }
        [XmlElement("Amountdueforpayment")]
        public Amount Amountdueforpayment { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public DocumentTotals()
        {
            Amountdueforpayment = new Amount();
            Roundingamount = new Amount();
            Paidamount = new Amount();
            InvoicetotalamountwithVAT = new Amount();
            InvoicetotalVATamountinaccountingcurrency = new Amount();
            InvoicetotalVATamount = new Amount();
            InvoicetotalamountwithoutVAT = new Amount();
            Sumofchargesondocumentlevel = new Amount();
            Sumofallowancesondocumentlevel = new Amount();
            SumofInvoicelinenetamount = new Amount();
        }
    }
}