// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("INVOICELINEType")]
    public class InvoiceLine
    {
        [XmlElement("Invoicelineidentifier")]
        public Identifier Invoicelineidentifier { get; set; }
        [XmlElement("Invoicelinenote")]
        public Text Invoicelinenote { get; set; }
        [XmlElement("Invoicelineobjectidentifier")]
        public Identifier Invoicelineobjectidentifier { get; set; }
        [XmlElement("Invoicedquantity")]
        public Quantity Invoicedquantity { get; set; }
        [XmlElement("Invoicedquantityunitofmeasurecode")]
        public Code Invoicedquantityunitofmeasurecode { get; set; }
        [XmlElement("Invoicelinenetamount")]
        public Amount Invoicelinenetamount { get; set; }
        [XmlElement("Referencedpurchaseorderlinereference")]
        public DocumentReference Referencedpurchaseorderlinereference { get; set; }
        [XmlElement("InvoicelineBuyeraccountingreference")]
        public Text InvoicelineBuyeraccountingreference { get; set; }
        [XmlElement("INVOICELINEPERIOD")]
        public InvoiceLinePeriod INVOICELINEPERIOD { get; set; }
        [XmlElement("INVOICELINEALLOWANCES")]
        public List<InvoiceLineAllowances> INVOICELINEALLOWANCES { get; set; }
        [XmlElement("INVOICELINECHARGES")]
        public List<InvoiceLlineCharges> INVOICELINECHARGES { get; set; }
        [XmlElement("PRICEDETAILS")]
        public PriceDetails PRICEDETAILS { get; set; }
        [XmlElement("LINEVATINFORMATION")]
        public List<LineVatInformation> LINEVATINFORMATION { get; set; }
        [XmlElement("ITEMINFORMATION")]
        public ItemInformation ITEMINFORMATION { get; set; }
        [XmlElement("SUBINVOICELINE")]
        public List<InvoiceLine> SUBINVOICELINE { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public InvoiceLine()
        {
            SUBINVOICELINE = new List<InvoiceLine>();
            ITEMINFORMATION = new ItemInformation();
            LINEVATINFORMATION = new List<LineVatInformation>();
            PRICEDETAILS = new PriceDetails();
            INVOICELINECHARGES = new List<InvoiceLlineCharges>();
            INVOICELINEALLOWANCES = new List<InvoiceLineAllowances>();
            INVOICELINEPERIOD = new InvoiceLinePeriod();
            InvoicelineBuyeraccountingreference = new Text();
            Referencedpurchaseorderlinereference = new DocumentReference();
            Invoicelinenetamount = new Amount();
            Invoicedquantityunitofmeasurecode = new Code();
            Invoicedquantity = new Quantity();
            Invoicelineobjectidentifier = new Identifier();
            Invoicelinenote = new Text();
            Invoicelineidentifier = new Identifier();
        }
    }
}