// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("INVOICELINEALLOWANCESType")]
    public class InvoiceLineAllowances
    {
        [XmlElement("Invoicelineallowanceamount")]
        public Amount Invoicelineallowanceamount { get; set; }
        [XmlElement("Invoicelineallowancebaseamount")]
        public Amount Invoicelineallowancebaseamount { get; set; }
        [XmlElement("Invoicelineallowancepercentage")]
        public Percentage Invoicelineallowancepercentage { get; set; }
        [XmlElement("Invoicelineallowancereason")]
        public Text Invoicelineallowancereason { get; set; }
        [XmlElement("Invoicelineallowancereasoncode")]
        public Code Invoicelineallowancereasoncode { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public InvoiceLineAllowances()
        {
            Invoicelineallowancereasoncode = new Code();
            Invoicelineallowancereason = new Text();
            Invoicelineallowancepercentage = new Percentage();
            Invoicelineallowancebaseamount = new Amount();
            Invoicelineallowanceamount = new Amount();
        }
    }
}