// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("INVOICELINECHARGESType")]
    public class InvoiceLlineCharges
    {
        [XmlElement("Invoicelinechargeamount")]
        public Amount Invoicelinechargeamount { get; set; }
        [XmlElement("Invoicelinechargebaseamount")]
        public Amount Invoicelinechargebaseamount { get; set; }
        [XmlElement("Invoicelinechargepercentage")]
        public Percentage Invoicelinechargepercentage { get; set; }
        [XmlElement("Invoicelinechargereason")]
        public Text Invoicelinechargereason { get; set; }
        [XmlElement("Invoicelinechargereasoncode")]
        public Code Invoicelinechargereasoncode { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public InvoiceLlineCharges()
        {
            Invoicelinechargereasoncode = new Code();
            Invoicelinechargereason = new Text();
            Invoicelinechargepercentage = new Percentage();
            Invoicelinechargebaseamount = new Amount();
            Invoicelinechargeamount = new Amount();
        }
    }
}