// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1", TypeName = "invoice")]
    [XmlRootAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1", IsNullable = false, ElementName = "invoice")]
    public class Invoice
    {
        [XmlElement("Invoicenumber")]
        public Identifier Invoicenumber { get; set; }
        [XmlElement("Invoiceissuedate")]
        public Date InvoiceIssueDate { get; set; }
        [XmlElement("Invoicetypecode")]
        public Code Invoicetypecode { get; set; }
        [XmlElement("Invoicecurrencycode")]
        public Code Invoicecurrencycode { get; set; }
        [XmlElement("VATaccountingcurrencycode")]
        public Code VATaccountingcurrencycode { get; set; }
        [XmlElement("Valueaddedtaxpointdate")]
        public Date ValueAddedTaxPointDate { get; set; }
        [XmlElement("Valueaddedtaxpointdatecode")]
        public Code Valueaddedtaxpointdatecode { get; set; }
        [XmlElement("Paymentduedate")]
        public Date PaymentDueDate { get; set; }
        [XmlElement("Buyerreference")]
        public Text BuyerReference { get; set; }
        [XmlElement("Projectreference")]
        public DocumentReference Projectreference { get; set; }
        [XmlElement("Contractreference")]
        public DocumentReference Contractreference { get; set; }
        [XmlElement("Purchaseorderreference")]
        public DocumentReference PurchaseOrderReference { get; set; }
        [XmlElement("Salesorderreference")]
        public DocumentReference Salesorderreference { get; set; }
        [XmlElement("Receivingadvicereference")]
        public DocumentReference Receivingadvicereference { get; set; }
        [XmlElement("Despatchadvicereference")]
        public DocumentReference Despatchadvicereference { get; set; }
        [XmlElement("Tenderorlotreference")]
        public DocumentReference Tenderorlotreference { get; set; }
        [XmlElement("Invoicedobjectidentifier")]
        public Identifier Invoicedobjectidentifier { get; set; }
        [XmlElement("Buyeraccountingreference")]
        public Text BuyerAccountingReference { get; set; }
        [XmlElement("Paymentterms")]
        public Text Paymentterms { get; set; }
        [XmlElement("INVOICENOTE")]
        public List<InvoiceNote> INVOICENOTE { get; set; }
        [XmlElement("PROCESSCONTROL")]
        public ProcessControl PROCESSCONTROL { get; set; }
        [XmlElement("PRECEDINGINVOICEREFERENCE")]
        public List<PrecedingInvoiceReference> PRECEDINGINVOICEREFERENCE { get; set; }
        [XmlElement("SELLER")]
        public Seller Seller { get; set; }
        [XmlElement("BUYER")]
        public Buyer Buyer { get; set; }
        [XmlElement("PAYEE")]
        public Payee Payee { get; set; }
        [XmlElement("SELLERTAXREPRESENTATIVEPARTY")]
        public SellerTaxRepresentativeParty SELLERTAXREPRESENTATIVEPARTY { get; set; }
        [XmlElement("DELIVERYINFORMATION")]
        public DeliveryInformation DeliveryInformation { get; set; }
        [XmlElement("INVOICINGPERIOD")]
        public InvoicingPeriod INVOICINGPERIOD { get; set; }
        [XmlElement("PAYMENTINSTRUCTIONS")]
        public PaymentInstructions PaymentInstruction { get; set; }
        [XmlElement("DOCUMENTLEVELALLOWANCES")]
        public List<DocumentLevelAllowances> DOCUMENTLEVELALLOWANCES { get; set; }
        [XmlElement("DOCUMENTLEVELCHARGES")]
        public List<DocumentLevelCharges> DOCUMENTLEVELCHARGES { get; set; }
        [XmlElement("DOCUMENTTOTALS")]
        public DocumentTotals DOCUMENTTOTALS { get; set; }
        [XmlElement("VATBREAKDOWN")]
        public List<VatBreakdown> VATBREAKDOWN { get; set; }
        [XmlElement("ADDITIONALSUPPORTINGDOCUMENTS")]
        public List<AdditionalDocuments> ADDITIONALSUPPORTINGDOCUMENTS { get; set; }
        [XmlElement("INVOICELINE")]
        public List<InvoiceLine> INVOICELINE { get; set; }
        [XmlElement("THIRDPARTYPAYMENT")]
        public List<ThirdPartyPayment> THIRDPARTYPAYMENT { get; set; }

        public Invoice()
        {
            THIRDPARTYPAYMENT = new List<ThirdPartyPayment>();
            INVOICELINE = new List<InvoiceLine>();
            ADDITIONALSUPPORTINGDOCUMENTS = new List<AdditionalDocuments>();
            VATBREAKDOWN = new List<VatBreakdown>();
            DOCUMENTTOTALS = new DocumentTotals();
            DOCUMENTLEVELCHARGES = new List<DocumentLevelCharges>();
            DOCUMENTLEVELALLOWANCES = new List<DocumentLevelAllowances>();
            PaymentInstruction = new PaymentInstructions();
            INVOICINGPERIOD = new InvoicingPeriod();
            DeliveryInformation = new DeliveryInformation();
            SELLERTAXREPRESENTATIVEPARTY = new SellerTaxRepresentativeParty();
            Payee = new Payee();
            Buyer = new Buyer();
            Seller = new Seller();
            PRECEDINGINVOICEREFERENCE = new List<PrecedingInvoiceReference>();
            PROCESSCONTROL = new ProcessControl();
            INVOICENOTE = new List<InvoiceNote>();
            Paymentterms = new Text();
            BuyerAccountingReference = new Text();
            Invoicedobjectidentifier = new Identifier();
            Tenderorlotreference = new DocumentReference();
            Despatchadvicereference = new DocumentReference();
            Receivingadvicereference = new DocumentReference();
            Salesorderreference = new DocumentReference();
            PurchaseOrderReference = new DocumentReference();
            Contractreference = new DocumentReference();
            Projectreference = new DocumentReference();
            BuyerReference = new Text();
            PaymentDueDate = new Date();
            Valueaddedtaxpointdatecode = new Code();
            ValueAddedTaxPointDate = new Date();
            VATaccountingcurrencycode = new Code();
            Invoicecurrencycode = new Code();
            Invoicetypecode = new Code();
            InvoiceIssueDate = new Date();
            Invoicenumber = new Identifier();
        }
    }
}