// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("ITEMINFORMATIONType")]
    public class ItemInformation
    {
        [XmlElement("Itemname")]
        public Text Itemname { get; set; }
        [XmlElement("Itemdescription")]
        public Text Itemdescription { get; set; }
        [XmlElement("ItemSellersidentifier")]
        public Identifier ItemSellersidentifier { get; set; }
        [XmlElement("ItemBuyersidentifier")]
        public Identifier ItemBuyersidentifier { get; set; }
        [XmlElement("Itemstandardidentifier")]
        public Identifier Itemstandardidentifier { get; set; }
        [XmlElement("Itemclassificationidentifier")]
        public List<Identifier> Itemclassificationidentifier { get; set; }
        [XmlElement("Itemcountryoforigin")]
        public Code Itemcountryoforigin { get; set; }
        [XmlElement("ITEMATTRIBUTES")]
        public List<ItemAttributes> ITEMATTRIBUTES { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public ItemInformation()
        {
            ITEMATTRIBUTES = new List<ItemAttributes>();
            Itemcountryoforigin = new Code();
            Itemclassificationidentifier = new List<Identifier>();
            Itemstandardidentifier = new Identifier();
            ItemBuyersidentifier = new Identifier();
            ItemSellersidentifier = new Identifier();
            Itemdescription = new Text();
            Itemname = new Text();
        }
    }
}