// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("PAYEEType")]
    public class Payee
    {
        [XmlElement("Payeename")]
        public Text Payeename { get; set; }
        [XmlElement("Payeeidentifier")]
        public Identifier Payeeidentifier { get; set; }
        [XmlElement("Payeelegalregistrationidentifier")]
        public Identifier Payeelegalregistrationidentifier { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public Payee()
        {
            Payeelegalregistrationidentifier = new Identifier();
            Payeeidentifier = new Identifier();
            Payeename = new Text();
        }
    }
}