// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("PAYMENTINSTRUCTIONSType")]
    public class PaymentInstructions
    {
        [XmlElement("Paymentmeanstypecode")]
        public Code Paymentmeanstypecode { get; set; }
        [XmlElement("Paymentmeanstext")]
        public Text Paymentmeanstext { get; set; }
        [XmlElement("Remittanceinformation")]
        public Text Remittanceinformation { get; set; }
        [XmlElement("CREDITTRANSFER")]
        public List<CreditTransfer> CREDITTRANSFER { get; set; }
        [XmlElement("PAYMENTCARDINFORMATION")]
        public PaymentCardInformation PAYMENTCARDINFORMATION { get; set; }
        [XmlElement("DIRECTDEBIT")]
        public DirectDebit DIRECTDEBIT { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public PaymentInstructions()
        {
            DIRECTDEBIT = new DirectDebit();
            PAYMENTCARDINFORMATION = new PaymentCardInformation();
            CREDITTRANSFER = new List<CreditTransfer>();
            Remittanceinformation = new Text();
            Paymentmeanstext = new Text();
            Paymentmeanstypecode = new Code();
        }
    }
}