// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace EHFleetXRechnung.Schemas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
    [XmlRootAttribute("SELLERType")]
    public class Seller
    {
        [XmlElement("Sellername")]
        public Text SellerName { get; set; }
        [XmlElement("Sellertradingname")]
        public Text SellerTradingname { get; set; }
        [XmlElement("Selleridentifier")]
        public List<Identifier> Selleridentifier { get; set; }
        [XmlElement("Sellerlegalregistrationidentifier")]
        public Identifier SellerLegalRegistrationIdentifier { get; set; }
        [XmlElement("SellerVATidentifier")]
        public Identifier SellerVATIdentifier { get; set; }
        [XmlElement("Sellertaxregistrationidentifier")]
        public Identifier Sellertaxregistrationidentifier { get; set; }
        [XmlElement("Selleradditionallegalinformation")]
        public Text Selleradditionallegalinformation { get; set; }
        [XmlElement("Sellerelectronicaddress")]
        public Identifier Sellerelectronicaddress { get; set; }
        [XmlElement("SELLERPOSTALADDRESS")]
        public SellerPostalAddress SellerPostaladdress { get; set; }
        [XmlElement("SELLERCONTACT")]
        public SellerContact SellerContact { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "id")]
        public string Id { get; set; }
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "token", AttributeName = "src")]
        public string Src { get; set; }

        public Seller()
        {
            SellerContact = new SellerContact();
            SellerPostaladdress = new SellerPostalAddress();
            Sellerelectronicaddress = new Identifier();
            Selleradditionallegalinformation = new Text();
            Sellertaxregistrationidentifier = new Identifier();
            SellerVATIdentifier = new Identifier();
            SellerLegalRegistrationIdentifier = new Identifier();
            Selleridentifier = new List<Identifier>();
            SellerTradingname = new Text();
            SellerName = new Text();
        }
    }
}