// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EHFleetXRechnung.Schemas
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
[XmlRootAttribute("SELLERPOSTALADDRESSType")]
public class SellerPostalAddress
{
        [XmlElement("Selleraddressline1")]
        public Text Selleraddressline1 { get; set; }
        [XmlElement("Selleraddressline2")]
        public Text Selleraddressline2 { get; set; }
        [XmlElement("Selleraddressline3")]
        public Text Selleraddressline3 { get; set; }
        [XmlElement("Sellercity")]
        public Text Sellercity { get; set; }
        [XmlElement("Sellerpostcode")]
        public Text Sellerpostcode { get; set; }
        [XmlElement("Sellercountrysubdivision")]
        public Text Sellercountrysubdivision { get; set; }
        [XmlElement("Sellercountrycode")]
        public Code Sellercountrycode { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="id")]
        public string Id { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="src")]
        public string Src { get; set; }
    
    public SellerPostalAddress()
    {
        Sellercountrycode = new Code();
        Sellercountrysubdivision = new Text();
        Sellerpostcode = new Text();
        Sellercity = new Text();
        Selleraddressline3 = new Text();
        Selleraddressline2 = new Text();
        Selleraddressline1 = new Text();
    }
}
}
#pragma warning restore
