// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EHFleetXRechnung.Schemas
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
[XmlRootAttribute("SELLERPOSTALADDRESSType")]
public class SellerPostalAddress
{
        [XmlElement("Selleraddressline1")]
        public Text SellerAddressline1 { get; set; }
        [XmlElement("Selleraddressline2")]
        public Text SellerAddressline2 { get; set; }
        [XmlElement("Selleraddressline3")]
        public Text SellerAddressline3 { get; set; }
        [XmlElement("Sellercity")]
        public Text SellerCity { get; set; }
        [XmlElement("Sellerpostcode")]
        public Text SellerPostcode { get; set; }
        [XmlElement("Sellercountrysubdivision")]
        public Text SellerCountrySubdivision { get; set; }
        [XmlElement("Sellercountrycode")]
        public Code SellerCountryCode { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="id")]
        public string Id { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="src")]
        public string Src { get; set; }
    
    public SellerPostalAddress()
    {
        SellerCountryCode = new Code();
        SellerCountrySubdivision = new Text();
        SellerPostcode = new Text();
        SellerCity = new Text();
        SellerAddressline3 = new Text();
        SellerAddressline2 = new Text();
        SellerAddressline1 = new Text();
    }
}
}
#pragma warning restore
