// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EHFleetXRechnung.Schemas
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1")]
[XmlRootAttribute("SELLERTAXREPRESENTATIVEPOSTALADDRESSType")]
public class SellerTaxRepresentativePostalAdress
{
        [XmlElement("Taxrepresentativeaddressline1")]
        public Text Taxrepresentativeaddressline1 { get; set; }
        [XmlElement("Taxrepresentativeaddressline2")]
        public Text Taxrepresentativeaddressline2 { get; set; }
        [XmlElement("Taxrepresentativeaddressline3")]
        public Text Taxrepresentativeaddressline3 { get; set; }
        [XmlElement("Taxrepresentativecity")]
        public Text Taxrepresentativecity { get; set; }
        [XmlElement("Taxrepresentativepostcode")]
        public Text Taxrepresentativepostcode { get; set; }
        [XmlElement("Taxrepresentativecountrysubdivision")]
        public Text Taxrepresentativecountrysubdivision { get; set; }
        [XmlElement("Taxrepresentativecountrycode")]
        public Code Taxrepresentativecountrycode { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="id")]
        public string Id { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="src")]
        public string Src { get; set; }
    
    public SellerTaxRepresentativePostalAdress()
    {
        Taxrepresentativecountrycode = new Code();
        Taxrepresentativecountrysubdivision = new Text();
        Taxrepresentativepostcode = new Text();
        Taxrepresentativecity = new Text();
        Taxrepresentativeaddressline3 = new Text();
        Taxrepresentativeaddressline2 = new Text();
        Taxrepresentativeaddressline1 = new Text();
    }
}
}
#pragma warning restore
