// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EHFleetXRechnung.Schemas
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1", TypeName="text")]
[XmlRootAttribute("text")]
public class Text
{
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="id")]
        public string Id { get; set; }
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token", AttributeName="src")]
        public string Src { get; set; }
        [XmlTextAttribute(DataType="token")]
        public string Value { get; set; }
}
}
#pragma warning restore
