//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbfahrtskontrolleAufgaben
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbfahrtskontrolleAufgaben()
        {
            this.AbfahrtskontrollePositionens = new HashSet<AbfahrtskontrollePositionen>();
            this.AbfahrtskontrolleVorlageAufgabens = new HashSet<AbfahrtskontrolleVorlageAufgaben>();
        }
    
        public int ID { get; set; }
        public string Kurzbezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public string Priorität { get; set; }
        public Nullable<bool> Pflicht { get; set; }
        public Nullable<bool> IstMangel { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public Nullable<bool> LetzterZugriff_Export { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbfahrtskontrollePositionen> AbfahrtskontrollePositionens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbfahrtskontrolleVorlageAufgaben> AbfahrtskontrolleVorlageAufgabens { get; set; }
    }
}
