//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbfahrtskontrollePositionen
    {
        public int ID { get; set; }
        public Nullable<int> AbfahrtskontrolleID { get; set; }
        public Nullable<int> AbfahrtskontrolleAufgabeID { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<System.DateTime> ErledigtDatum { get; set; }
        public Nullable<bool> Ergebnis { get; set; }
        public string Zusatzangabe { get; set; }
        public Nullable<int> MangelID { get; set; }
        public string Bemerkung { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    
        public virtual AbfahrtskontrolleAufgaben AbfahrtskontrolleAufgaben { get; set; }
        public virtual AbfahrtskontrolleKopf AbfahrtskontrolleKopf { get; set; }
    }
}
