//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbfahrtskontrolleVorlageAufgaben
    {
        public int ID { get; set; }
        public int AbfahrtskontrolleVorlageID { get; set; }
        public int AbfahrtskontrolleAufgabeID { get; set; }
        public Nullable<int> Reihenfolge { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    
        public virtual AbfahrtskontrolleAufgaben AbfahrtskontrolleAufgaben { get; set; }
        public virtual AbfahrtskontrolleVorlagen AbfahrtskontrolleVorlagen { get; set; }
    }
}
