//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbfahrtskontrolleKopf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbfahrtskontrolleKopf()
        {
            this.AbfahrtskontrollePositionens = new HashSet<AbfahrtskontrollePositionen>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PersonalNr { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public System.DateTime Kontrolldatum { get; set; }
        public string Kontrollort { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string Kurzbezeichnung { get; set; }
        public Nullable<decimal> Kilometerstand { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<System.DateTime> ErledigtDatum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbfahrtskontrollePositionen> AbfahrtskontrollePositionens { get; set; }
    }
}
