//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anmeldungen
    {
        public string Anmeldename { get; set; }
        public string Hostname { get; set; }
        public System.DateTime Zeitpunkt { get; set; }
        public int ProzessID { get; set; }
    }
}
