//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public int ID { get; set; }
        public string ArtikelNr { get; set; }
        public string Artikelbez { get; set; }
        public string ArtikelbezLang { get; set; }
        public string Kategorie { get; set; }
        public string Artikelgruppe { get; set; }
        public Nullable<decimal> Einkaufspreis { get; set; }
        public Nullable<decimal> BewertungsEk { get; set; }
        public string EANCode { get; set; }
        public string Mengeneinheit { get; set; }
        public string Lieferant { get; set; }
        public string Lagerstelle { get; set; }
        public string Lagerplatz { get; set; }
        public Nullable<int> Mindestmenge { get; set; }
        public Nullable<int> Mindestbestellmenge { get; set; }
        public Nullable<bool> keinEtikett { get; set; }
        public Nullable<bool> keinLager { get; set; }
        public Nullable<bool> Altteil { get; set; }
        public Nullable<decimal> tempBEK { get; set; }
        public string MwSt { get; set; }
        public string Gegenkonto { get; set; }
        public Nullable<bool> ohneAufschlag { get; set; }
        public Nullable<bool> ohneRabatt { get; set; }
        public Nullable<bool> Auslage { get; set; }
        public Nullable<bool> Archiv { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
