//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikelpreisliste
    {
        public int ID { get; set; }
        public Nullable<int> ArtikelID { get; set; }
        public Nullable<int> KundenID { get; set; }
        public Nullable<int> LieferantenID { get; set; }
        public Nullable<decimal> LEK { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string HerstellerNr { get; set; }
        public string EANCode { get; set; }
        public string BestellNr { get; set; }
        public string Bestellbez { get; set; }
        public string TeileHinweis { get; set; }
        public Nullable<decimal> Listenpreis { get; set; }
        public Nullable<decimal> EKRabatt { get; set; }
        public Nullable<decimal> VPE { get; set; }
        public Nullable<int> Preisgruppe { get; set; }
        public Nullable<int> Prozentgruppe { get; set; }
        public Nullable<decimal> Prozentsatz { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
