//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtikelFreifelder
    {
        public int ID { get; set; }
        public int ArtikelID { get; set; }
        public string Freifeld0 { get; set; }
        public string Freifeld1 { get; set; }
        public string Freifeld2 { get; set; }
        public string Freifeld3 { get; set; }
        public string Freifeld4 { get; set; }
        public string Freifeld5 { get; set; }
        public string Freifeld6 { get; set; }
        public string Freifeld7 { get; set; }
        public string Freifeld8 { get; set; }
        public string Freifeld9 { get; set; }
        public string Freifeld10 { get; set; }
        public string Freifeld11 { get; set; }
        public string Freifeld12 { get; set; }
        public string Freifeld13 { get; set; }
        public string Freifeld14 { get; set; }
        public string Freifeld15 { get; set; }
        public string Freifeld16 { get; set; }
        public string Freifeld17 { get; set; }
        public string Freifeld18 { get; set; }
        public string Freifeld19 { get; set; }
        public Nullable<System.DateTime> Freifeld20 { get; set; }
        public Nullable<System.DateTime> Freifeld21 { get; set; }
        public Nullable<System.DateTime> Freifeld22 { get; set; }
        public Nullable<System.DateTime> Freifeld23 { get; set; }
        public Nullable<System.DateTime> Freifeld24 { get; set; }
        public Nullable<bool> Freifeld25 { get; set; }
        public Nullable<bool> Freifeld26 { get; set; }
        public Nullable<bool> Freifeld27 { get; set; }
        public Nullable<bool> Freifeld28 { get; set; }
        public Nullable<bool> Freifeld29 { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
