//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikellagerstellen
    {
        public int ID { get; set; }
        public int ArtikelID { get; set; }
        public string Lagerstelle { get; set; }
        public string Lagerplatz { get; set; }
        public Nullable<decimal> Mindestmenge { get; set; }
        public Nullable<decimal> Mindestbestellmenge { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public Nullable<decimal> tempBEK { get; set; }
    }
}
