//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Berichte
    {
        public int ID { get; set; }
        public string Gruppe { get; set; }
        public string Name { get; set; }
        public string Beschreibung { get; set; }
        public string Abfrage { get; set; }
        public string Filter { get; set; }
        public string PfadundDatei { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
