//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestellungBuchungsstapel
    {
        public int ID { get; set; }
        public Nullable<int> BestellNr { get; set; }
        public string Bezeichnung { get; set; }
        public string BelegNr { get; set; }
        public System.DateTime Belegdatum { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public Nullable<decimal> Gesamtpreis { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public string KreditorNr { get; set; }
        public Nullable<int> LieferantenNr { get; set; }
        public string Kostenstelle { get; set; }
        public string KategorieNr { get; set; }
        public string Kategorie { get; set; }
        public string Erlöskonto { get; set; }
        public string Gegenkonto { get; set; }
        public string Aufwandskonto { get; set; }
        public Nullable<int> SkontoTage { get; set; }
        public Nullable<decimal> SkontoProzent { get; set; }
        public Nullable<int> NettoTage { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
