//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestellungKopf
    {
        public int BestellNr { get; set; }
        public Nullable<int> LieferantenNr { get; set; }
        public Nullable<int> KundenNr { get; set; }
        public Nullable<int> PersonalNr { get; set; }
        public Nullable<System.DateTime> Bestelldatum { get; set; }
        public string EinkaufBestellNummer { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<System.DateTime> ErforderlichAb { get; set; }
        public Nullable<System.DateTime> Zusagedatum { get; set; }
        public string Liefername { get; set; }
        public string Lieferadresse { get; set; }
        public string Lieferort { get; set; }
        public string Bundesland { get; set; }
        public string BundeslandOderRegion { get; set; }
        public string BestimmungsortPLZ { get; set; }
        public string Bestimmungsland { get; set; }
        public string LieferantTelefonnummer { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public string Versandart { get; set; }
        public Nullable<decimal> Frachtkosten { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public Nullable<decimal> Umsatzsteuersatz { get; set; }
        public string LieferscheinNr { get; set; }
        public string RechnungsNr { get; set; }
        public Nullable<System.DateTime> Rechnungsdatum { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<bool> Exportiert { get; set; }
        public Nullable<bool> ExportiertInterface { get; set; }
        public Nullable<bool> Gebucht { get; set; }
        public Nullable<bool> Storno { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public string Standort { get; set; }
    }
}
