//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class D11S
    {
        public int ID { get; set; }
        public string DriverCardNr { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public Nullable<System.DateTime> LT_Day { get; set; }
        public Nullable<int> LT_AcDayTime { get; set; }
        public string LT_AcDayTimeH { get; set; }
        public Nullable<int> LT_WeekTime { get; set; }
        public string LT_WeekTimeH { get; set; }
        public Nullable<int> LT_TotalTime { get; set; }
        public string LT_TotalTimeH { get; set; }
        public Nullable<int> LT_RemWeekTime { get; set; }
        public string LT_RemWeekTimeH { get; set; }
        public Nullable<int> LT_RemTotalTime { get; set; }
        public string LT_RemTotalTimeH { get; set; }
        public string FilenameDDD { get; set; }
    }
}
