//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EHFleetEntities : DbContext
    {
        public EHFleetEntities()
            : this("name=EHFleetEntities")
        {
        }
    
        public EHFleetEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbfahrtskontrolleAufgaben> AbfahrtskontrolleAufgabens { get; set; }
        public virtual DbSet<AbfahrtskontrolleDokumente> AbfahrtskontrolleDokumentes { get; set; }
        public virtual DbSet<AbfahrtskontrolleKopf> AbfahrtskontrolleKopfs { get; set; }
        public virtual DbSet<AbfahrtskontrollePositionen> AbfahrtskontrollePositionens { get; set; }
        public virtual DbSet<AbfahrtskontrolleVorlageAufgaben> AbfahrtskontrolleVorlageAufgabens { get; set; }
        public virtual DbSet<AbfahrtskontrolleVorlagen> AbfahrtskontrolleVorlagens { get; set; }
        public virtual DbSet<AbfahrtskontrolleVorlagenZuordnung> AbfahrtskontrolleVorlagenZuordnungs { get; set; }
        public virtual DbSet<Achsarten> Achsartens { get; set; }
        public virtual DbSet<AchsartenZuordnung> AchsartenZuordnungs { get; set; }
        public virtual DbSet<Anmeldungen> Anmeldungens { get; set; }
        public virtual DbSet<AppModulVersion> AppModulVersions { get; set; }
        public virtual DbSet<Artikel> Artikels { get; set; }
        public virtual DbSet<ArtikelDokumente> ArtikelDokumentes { get; set; }
        public virtual DbSet<Artikelgruppen> Artikelgruppens { get; set; }
        public virtual DbSet<ArtikelgruppenZuordnung> ArtikelgruppenZuordnungs { get; set; }
        public virtual DbSet<Artikellagerstellen> Artikellagerstellens { get; set; }
        public virtual DbSet<Artikelpreisliste> Artikelpreislistes { get; set; }
        public virtual DbSet<Auftragsart> Auftragsarts { get; set; }
        public virtual DbSet<Auftragsstatu> Auftragsstatus { get; set; }
        public virtual DbSet<AWTexte> AWTextes { get; set; }
        public virtual DbSet<Banken> Bankens { get; set; }
        public virtual DbSet<Belegart> Belegarts { get; set; }
        public virtual DbSet<Berechtigungen> Berechtigungens { get; set; }
        public virtual DbSet<Berichte> Berichtes { get; set; }
        public virtual DbSet<BestellungBuchungsjournal> BestellungBuchungsjournals { get; set; }
        public virtual DbSet<BestellungBuchungsstapel> BestellungBuchungsstapels { get; set; }
        public virtual DbSet<Bestellungdetail> Bestellungdetails { get; set; }
        public virtual DbSet<BestellungDokumente> BestellungDokumentes { get; set; }
        public virtual DbSet<BestellungFreifelder> BestellungFreifelders { get; set; }
        public virtual DbSet<BestellungKopf> BestellungKopfs { get; set; }
        public virtual DbSet<BKFQKenntnisbereiche> BKFQKenntnisbereiches { get; set; }
        public virtual DbSet<BKFQModule> BKFQModules { get; set; }
        public virtual DbSet<BKFQModulgruppen> BKFQModulgruppens { get; set; }
        public virtual DbSet<BKFQQualifizierungDokumente> BKFQQualifizierungDokumentes { get; set; }
        public virtual DbSet<BKFQQualifizierungen> BKFQQualifizierungens { get; set; }
        public virtual DbSet<BKFQSchulungen> BKFQSchulungens { get; set; }
        public virtual DbSet<D11E> D11E { get; set; }
        public virtual DbSet<D11S> D11S { get; set; }
        public virtual DbSet<DatenbankVersion> DatenbankVersions { get; set; }
        public virtual DbSet<Fahrerlaubnisklassen> Fahrerlaubnisklassens { get; set; }
        public virtual DbSet<FahrzeugDokumente> FahrzeugDokumentes { get; set; }
        public virtual DbSet<Fahrzeuge> Fahrzeuges { get; set; }
        public virtual DbSet<Fahrzeugfälligkeiten> Fahrzeugfälligkeiten { get; set; }
        public virtual DbSet<Fahrzeugfälligkeitsarten> Fahrzeugfälligkeitsarten { get; set; }
        public virtual DbSet<FahrzeugFinanzierung> FahrzeugFinanzierungs { get; set; }
        public virtual DbSet<FahrzeugFreifelder> FahrzeugFreifelders { get; set; }
        public virtual DbSet<FahrzeugFreifelderDaten> FahrzeugFreifelderDatens { get; set; }
        public virtual DbSet<FahrzeugFreifelderFelddefinition> FahrzeugFreifelderFelddefinitions { get; set; }
        public virtual DbSet<Fahrzeuggruppen> Fahrzeuggruppens { get; set; }
        public virtual DbSet<FahrzeuggruppenZuordnung> FahrzeuggruppenZuordnungs { get; set; }
        public virtual DbSet<Fahrzeugkosten> Fahrzeugkostens { get; set; }
        public virtual DbSet<FahrzeugLeasing> FahrzeugLeasings { get; set; }
        public virtual DbSet<Fahrzeugtypen> Fahrzeugtypens { get; set; }
        public virtual DbSet<FahrzeugtypenZuordnung> FahrzeugtypenZuordnungs { get; set; }
        public virtual DbSet<FremdrechnungBuchungsjournal> FremdrechnungBuchungsjournals { get; set; }
        public virtual DbSet<FremdrechnungBuchungsstapel> FremdrechnungBuchungsstapels { get; set; }
        public virtual DbSet<FremdrechnungDokumente> FremdrechnungDokumentes { get; set; }
        public virtual DbSet<FremdrechnungFreifelder> FremdrechnungFreifelders { get; set; }
        public virtual DbSet<FremdrechnungKopf> FremdrechnungKopfs { get; set; }
        public virtual DbSet<FührerscheinDokumente> FührerscheinDokumente { get; set; }
        public virtual DbSet<ILVRechnungBuchungsjournal> ILVRechnungBuchungsjournals { get; set; }
        public virtual DbSet<ILVRechnungBuchungsstapel> ILVRechnungBuchungsstapels { get; set; }
        public virtual DbSet<ILVRechnungdetail> ILVRechnungdetails { get; set; }
        public virtual DbSet<ILVRechnungDokumente> ILVRechnungDokumentes { get; set; }
        public virtual DbSet<ILVRechnungFreifelder> ILVRechnungFreifelders { get; set; }
        public virtual DbSet<ILVRechnungKopf> ILVRechnungKopfs { get; set; }
        public virtual DbSet<Inventurliste> Inventurlistes { get; set; }
        public virtual DbSet<Kategorie> Kategories { get; set; }
        public virtual DbSet<KategorieErlöskonten> KategorieErlöskonten { get; set; }
        public virtual DbSet<Kostenstelle> Kostenstelles { get; set; }
        public virtual DbSet<Kostenträger> Kostenträger { get; set; }
        public virtual DbSet<Kostenvoranschlagdetail> Kostenvoranschlagdetails { get; set; }
        public virtual DbSet<KostenvoranschlagDokumente> KostenvoranschlagDokumentes { get; set; }
        public virtual DbSet<KostenvoranschlagFreifelder> KostenvoranschlagFreifelders { get; set; }
        public virtual DbSet<KostenvoranschlagKopf> KostenvoranschlagKopfs { get; set; }
        public virtual DbSet<Kreditkartenfirman> Kreditkartenfirmen { get; set; }
        public virtual DbSet<KreditkartenfirmenZuordnung> KreditkartenfirmenZuordnungs { get; set; }
        public virtual DbSet<Kunden> Kundens { get; set; }
        public virtual DbSet<Kundengruppen> Kundengruppens { get; set; }
        public virtual DbSet<KundengruppenZuordnung> KundengruppenZuordnungs { get; set; }
        public virtual DbSet<Lager> Lagers { get; set; }
        public virtual DbSet<Lagerbewegungen> Lagerbewegungens { get; set; }
        public virtual DbSet<Länder> Länder { get; set; }
        public virtual DbSet<Lieferanten> Lieferantens { get; set; }
        public virtual DbSet<Mangelart> Mangelarts { get; set; }
        public virtual DbSet<MangelDokumente> MangelDokumentes { get; set; }
        public virtual DbSet<MangelFreifelder> MangelFreifelders { get; set; }
        public virtual DbSet<MangelKopf> MangelKopfs { get; set; }
        public virtual DbSet<ManuelleRechnungdetail> ManuelleRechnungdetails { get; set; }
        public virtual DbSet<ManuelleRechnungDokumente> ManuelleRechnungDokumentes { get; set; }
        public virtual DbSet<ManuelleRechnungFreifelder> ManuelleRechnungFreifelders { get; set; }
        public virtual DbSet<ManuelleRechnungKopf> ManuelleRechnungKopfs { get; set; }
        public virtual DbSet<Mautbuchungen> Mautbuchungens { get; set; }
        public virtual DbSet<MautErlöskonten> MautErlöskonten { get; set; }
        public virtual DbSet<Mengeneinheit> Mengeneinheits { get; set; }
        public virtual DbSet<Menüpunkte> Menüpunkte { get; set; }
        public virtual DbSet<Mietabrechnungdetail> Mietabrechnungdetails { get; set; }
        public virtual DbSet<MietabrechnungErlöskonten> MietabrechnungErlöskonten { get; set; }
        public virtual DbSet<MietabrechnungKopf> MietabrechnungKopfs { get; set; }
        public virtual DbSet<MobileGeräte> MobileGeräte { get; set; }
        public virtual DbSet<Musteraufträge> Musteraufträge { get; set; }
        public virtual DbSet<MusteraufträgeArtikel> MusteraufträgeArtikel { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Parameterdetail> Parameterdetails { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<PersonalBenachrichtigungen> PersonalBenachrichtigungens { get; set; }
        public virtual DbSet<PersonalDokumente> PersonalDokumentes { get; set; }
        public virtual DbSet<PersonalErlöskonten> PersonalErlöskonten { get; set; }
        public virtual DbSet<PersonalFahrerlaubnisklassen> PersonalFahrerlaubnisklassens { get; set; }
        public virtual DbSet<PersonalFahrzeugZuordnung> PersonalFahrzeugZuordnungs { get; set; }
        public virtual DbSet<Personalfälligkeiten> Personalfälligkeiten { get; set; }
        public virtual DbSet<Personalfälligkeitsarten> Personalfälligkeitsarten { get; set; }
        public virtual DbSet<PersonalFreifelder> PersonalFreifelders { get; set; }
        public virtual DbSet<PersonalFreifelderDaten> PersonalFreifelderDatens { get; set; }
        public virtual DbSet<PersonalFreifelderFelddefinition> PersonalFreifelderFelddefinitions { get; set; }
        public virtual DbSet<PersonalFührerscheine> PersonalFührerscheine { get; set; }
        public virtual DbSet<PersonalFührerscheinkontrollen> PersonalFührerscheinkontrollen { get; set; }
        public virtual DbSet<PersonalRFIDFührerschein> PersonalRFIDFührerschein { get; set; }
        public virtual DbSet<Produktart> Produktarts { get; set; }
        public virtual DbSet<ProduktartErlöskonten> ProduktartErlöskonten { get; set; }
        public virtual DbSet<Produktgruppen> Produktgruppens { get; set; }
        public virtual DbSet<ProduktgruppenZuordnung> ProduktgruppenZuordnungs { get; set; }
        public virtual DbSet<Rechnungdetail> Rechnungdetails { get; set; }
        public virtual DbSet<RechnungdetailVorschau> RechnungdetailVorschaus { get; set; }
        public virtual DbSet<RechnungDokumente> RechnungDokumentes { get; set; }
        public virtual DbSet<RechnungFreifelder> RechnungFreifelders { get; set; }
        public virtual DbSet<RechnungKopf> RechnungKopfs { get; set; }
        public virtual DbSet<RechnungKopfVorschau> RechnungKopfVorschaus { get; set; }
        public virtual DbSet<Rechnungstexte> Rechnungstextes { get; set; }
        public virtual DbSet<Reifen> Reifens { get; set; }
        public virtual DbSet<Reifenbewegungen> Reifenbewegungens { get; set; }
        public virtual DbSet<Reifenfelgen> Reifenfelgens { get; set; }
        public virtual DbSet<Reifengrössen> Reifengrössen { get; set; }
        public virtual DbSet<Reifenhersteller> Reifenherstellers { get; set; }
        public virtual DbSet<Reifentypen> Reifentypens { get; set; }
        public virtual DbSet<RFIDFührerscheinkontrollen> RFIDFührerscheinkontrollen { get; set; }
        public virtual DbSet<SammelrechnungKopf> SammelrechnungKopfs { get; set; }
        public virtual DbSet<Spritbuchungen> Spritbuchungens { get; set; }
        public virtual DbSet<Standorte> Standortes { get; set; }
        public virtual DbSet<StandorteFahrzeugZuordnung> StandorteFahrzeugZuordnungs { get; set; }
        public virtual DbSet<StandorteFahrzeugZuordnungErweitert> StandorteFahrzeugZuordnungErweiterts { get; set; }
        public virtual DbSet<StandorteLagerZuordnung> StandorteLagerZuordnungs { get; set; }
        public virtual DbSet<StandortePersonalZuordnung> StandortePersonalZuordnungs { get; set; }
        public virtual DbSet<Steuersätze> Steuersätze { get; set; }
        public virtual DbSet<Tankabrechnungdetail> Tankabrechnungdetails { get; set; }
        public virtual DbSet<TankabrechnungDokumente> TankabrechnungDokumentes { get; set; }
        public virtual DbSet<TankabrechnungFreifelder> TankabrechnungFreifelders { get; set; }
        public virtual DbSet<TankabrechnungKopf> TankabrechnungKopfs { get; set; }
        public virtual DbSet<TerminAbrechnung> TerminAbrechnungs { get; set; }
        public virtual DbSet<TerminAbrechnungVorlage> TerminAbrechnungVorlages { get; set; }
        public virtual DbSet<TerminDokumente> TerminDokumentes { get; set; }
        public virtual DbSet<TerminFreifelder> TerminFreifelders { get; set; }
        public virtual DbSet<TerminKategorien> TerminKategoriens { get; set; }
        public virtual DbSet<TerminKopf> TerminKopfs { get; set; }
        public virtual DbSet<Unfallart> Unfallarts { get; set; }
        public virtual DbSet<UnfallDokumente> UnfallDokumentes { get; set; }
        public virtual DbSet<UnfallFreifelder> UnfallFreifelders { get; set; }
        public virtual DbSet<UnfallFremdrechnung> UnfallFremdrechnungs { get; set; }
        public virtual DbSet<UnfallKopf> UnfallKopfs { get; set; }
        public virtual DbSet<UnfallWerkstattauftrag> UnfallWerkstattauftrags { get; set; }
        public virtual DbSet<Versandart> Versandarts { get; set; }
        public virtual DbSet<Werbefläche> Werbefläche { get; set; }
        public virtual DbSet<WerbeflächeZuordnung> WerbeflächeZuordnung { get; set; }
        public virtual DbSet<WerbungDokumente> WerbungDokumentes { get; set; }
        public virtual DbSet<WerbungFreifelder> WerbungFreifelders { get; set; }
        public virtual DbSet<WerbungKopf> WerbungKopfs { get; set; }
        public virtual DbSet<WerkstattauftragAWTexte> WerkstattauftragAWTextes { get; set; }
        public virtual DbSet<WerkstattauftragDokumente> WerkstattauftragDokumentes { get; set; }
        public virtual DbSet<WerkstattauftragFreifelder> WerkstattauftragFreifelders { get; set; }
        public virtual DbSet<WerkstattauftragKopf> WerkstattauftragKopfs { get; set; }
        public virtual DbSet<WerkstattauftragLohn> WerkstattauftragLohns { get; set; }
        public virtual DbSet<WerkstattauftragPositionen> WerkstattauftragPositionens { get; set; }
        public virtual DbSet<Zahlungsziele> Zahlungszieles { get; set; }
        public virtual DbSet<Zeiterfassung> Zeiterfassungs { get; set; }
        public virtual DbSet<ArtikelFreifelder> ArtikelFreifelders { get; set; }
        public virtual DbSet<KundenExterneMandanten> KundenExterneMandantens { get; set; }
        public virtual DbSet<KundenExterneMandantenSubunternehmer> KundenExterneMandantenSubunternehmers { get; set; }
        public virtual DbSet<KundenFreifelder> KundenFreifelders { get; set; }
        public virtual DbSet<LieferantenFreifelder> LieferantenFreifelders { get; set; }
        public virtual DbSet<Lizenzen> Lizenzens { get; set; }
        public virtual DbSet<ManuelleRechnungBuchungsjournal> ManuelleRechnungBuchungsjournals { get; set; }
        public virtual DbSet<ManuelleRechnungBuchungsstapel> ManuelleRechnungBuchungsstapels { get; set; }
        public virtual DbSet<Mautknoten> Mautknotens { get; set; }
        public virtual DbSet<RechnungBuchungsjournal> RechnungBuchungsjournals { get; set; }
        public virtual DbSet<RechnungBuchungsstapel> RechnungBuchungsstapels { get; set; }
        public virtual DbSet<TankabrechnungBuchungsjournal> TankabrechnungBuchungsjournals { get; set; }
        public virtual DbSet<TankabrechnungBuchungsstapel> TankabrechnungBuchungsstapels { get; set; }
    }
}
