//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FahrzeugLeasing
    {
        public int ID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string VertragsNr { get; set; }
        public string Vertragsbezeichnung { get; set; }
        public Nullable<int> Leasinggeber { get; set; }
        public Nullable<int> LieferantenNr { get; set; }
        public Nullable<int> Laufzeit { get; set; }
        public Nullable<System.DateTime> Vertragsbeginn { get; set; }
        public Nullable<decimal> Fahrleistung { get; set; }
        public Nullable<decimal> Leasingfaktor { get; set; }
        public Nullable<decimal> Leasingrate { get; set; }
        public Nullable<decimal> Berechnungsgrundlage { get; set; }
        public Nullable<decimal> Sonderzahlung { get; set; }
        public Nullable<decimal> SonderzahlungE { get; set; }
        public Nullable<decimal> ZzglKosten { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
