//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeugkosten
    {
        public int ID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string Kategorie { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<decimal> EPreis { get; set; }
        public Nullable<System.DateTime> vonDatum { get; set; }
        public Nullable<System.DateTime> bisDatum { get; set; }
        public Nullable<System.DateTime> Belegdatum { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<int> UnfallID { get; set; }
        public Nullable<bool> variabel { get; set; }
        public Nullable<int> FremdrechnungID { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public Nullable<bool> Altteil { get; set; }
        public string Bemerkung { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
