//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class FahrzeugFinanzierung
    {
        public int ID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string VertragsNr { get; set; }
        public string Vertragsbezeichnung { get; set; }
        public Nullable<int> Darlehensgeber { get; set; }
        public Nullable<int> LieferantenNr { get; set; }
        public Nullable<int> Laufzeit { get; set; }
        public Nullable<System.DateTime> Vertragsbeginn { get; set; }
        public Nullable<decimal> Fahrleistung { get; set; }
        public Nullable<decimal> Zinssatz { get; set; }
        public Nullable<decimal> EffektiverZinssatz { get; set; }
        public Nullable<decimal> Berechnungsgrundlage { get; set; }
        public Nullable<decimal> Anzahlung { get; set; }
        public Nullable<decimal> ZzglKostenEinmalig { get; set; }
        public Nullable<decimal> ZzglKostenMonatlich { get; set; }
        public Nullable<decimal> Nettodarlehensbetrag { get; set; }
        public Nullable<decimal> Zinsen { get; set; }
        public Nullable<decimal> Darlehenssumme { get; set; }
        public Nullable<decimal> Finanzierungsrate { get; set; }
        public Nullable<decimal> Schlußrate { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
