//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeuge
    {
        public int ID { get; set; }
        public string Aktionsart { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string KFZNrA { get; set; }
        public string Kennzeichen { get; set; }
        public Nullable<decimal> Kodiersteck { get; set; }
        public string Kreditkart { get; set; }
        public string LauflEinheit { get; set; }
        public Nullable<decimal> Kilometerstand { get; set; }
        public Nullable<int> MaxAbgabe1 { get; set; }
        public Nullable<int> MaxAbgabe2 { get; set; }
        public Nullable<int> MaxAbgabe3 { get; set; }
        public Nullable<int> MaxAbgabe4 { get; set; }
        public Nullable<int> MaxAbgabe5 { get; set; }
        public Nullable<int> MaxAbgabe6 { get; set; }
        public Nullable<int> MaxAbgabe7 { get; set; }
        public Nullable<int> MaxAbgabe8 { get; set; }
        public Nullable<int> MaxAbgabe9 { get; set; }
        public Nullable<int> MaxAbgabe10 { get; set; }
        public Nullable<int> MaxAbgabe11 { get; set; }
        public Nullable<int> MaxAbgabe12 { get; set; }
        public Nullable<int> Sollvorgabe1 { get; set; }
        public Nullable<int> Sollvorgabe2 { get; set; }
        public Nullable<int> Sollvorgabe3 { get; set; }
        public Nullable<int> Sollvorgabe4 { get; set; }
        public Nullable<int> Sollvorgabe5 { get; set; }
        public Nullable<int> Sollvorgabe6 { get; set; }
        public Nullable<int> Sollvorgabe7 { get; set; }
        public Nullable<int> Sollvorgabe8 { get; set; }
        public Nullable<int> Sollvorgabe9 { get; set; }
        public Nullable<int> Sollvorgabe10 { get; set; }
        public Nullable<int> Sollvorgabe11 { get; set; }
        public Nullable<int> Sollvorgabe12 { get; set; }
        public string Kundennummer { get; set; }
        public string Reserve { get; set; }
        public string Hersteller { get; set; }
        public string Typ { get; set; }
        public string FahrgestellNr { get; set; }
        public Nullable<decimal> Anfangskm { get; set; }
        public Nullable<System.DateTime> Zulassung { get; set; }
        public Nullable<bool> IstAnhänger { get; set; }
        public string VersicherungsNr { get; set; }
        public string VersicherungsGesellschaft { get; set; }
        public string Reifengröße1 { get; set; }
        public string Reifengröße2 { get; set; }
        public string Reifengröße3 { get; set; }
        public string Reifengröße4 { get; set; }
        public string Bild { get; set; }
        public string Miniaturbild { get; set; }
        public string Fahrzeugbrief { get; set; }
        public Nullable<int> Achsanzahl { get; set; }
        public string Schlüsselnr { get; set; }
        public string Schadstoffklasse { get; set; }
        public string Bemerkung { get; set; }
        public string Kostenstelle { get; set; }
        public string Kostenträger { get; set; }
        public Nullable<bool> Aktuell { get; set; }
        public Nullable<int> KundenNr { get; set; }
        public Nullable<bool> Fremdfahrzeug { get; set; }
        public Nullable<decimal> Gebrauchtwagenwert { get; set; }
        public Nullable<System.DateTime> Bewertungsdatum { get; set; }
        public Nullable<decimal> Ap { get; set; }
        public Nullable<decimal> Wp { get; set; }
        public Nullable<decimal> Erw { get; set; }
        public Nullable<decimal> IA { get; set; }
        public Nullable<int> Bt { get; set; }
        public Nullable<System.DateTime> Inbetriebnahmedatum { get; set; }
        public Nullable<System.DateTime> Ausfalldatum { get; set; }
        public string EquipmentId { get; set; }
        public Nullable<bool> DTCO { get; set; }
        public string DTCOKennzeichen { get; set; }
        public Nullable<int> StandardFahrerID { get; set; }
        public Nullable<int> StandardAnhängerID { get; set; }
        public string Produktgruppe { get; set; }
        public Nullable<bool> Vorsteuerabzug { get; set; }
        public Nullable<bool> Poolfahrzeug { get; set; }
        public Nullable<decimal> CO2EmissionGKm { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
