//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class FremdrechnungKopf
    {
        public int ID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public int LieferantenNr { get; set; }
        public string Bezeichnung { get; set; }
        public string Bemerkung { get; set; }
        public string BelegNr { get; set; }
        public System.DateTime Belegdatum { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public string LieferscheinNr { get; set; }
        public string Versandart { get; set; }
        public decimal Gesamtbetrag { get; set; }
        public string MwSt { get; set; }
        public Nullable<double> MwStProzent { get; set; }
        public Nullable<int> SkontoTage { get; set; }
        public Nullable<double> SkontoProzent { get; set; }
        public Nullable<int> NettoTage { get; set; }
        public string Kostenstelle { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<bool> Exportiert { get; set; }
        public Nullable<bool> Gebucht { get; set; }
        public Nullable<bool> Storno { get; set; }
        public Nullable<int> SyncWAID { get; set; }
        public Nullable<int> SyncTAID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
