//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILVRechnungdetail
    {
        public int RechnungsdetailNr { get; set; }
        public Nullable<int> RechnungsNr { get; set; }
        public Nullable<int> BestellNr { get; set; }
        public Nullable<int> ArtikelNr { get; set; }
        public string freieArtikelNr { get; set; }
        public string freieArtikelbez { get; set; }
        public string freieArtikeleinheit { get; set; }
        public string freieArtikelkategorie { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public Nullable<decimal> EPreis { get; set; }
        public string Zahlungsfristen { get; set; }
        public Nullable<decimal> Rabatt { get; set; }
        public Nullable<decimal> Gesamtpreis { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> WAID { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public string KategorieSonstige { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
