//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILVRechnungBuchungsjournal
    {
        public int ID { get; set; }
        public Nullable<int> RechnungsNr { get; set; }
        public Nullable<System.DateTime> Rechnungsdatum { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public Nullable<decimal> Gesamtpreis { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public string DebitorNr { get; set; }
        public Nullable<int> KundenNr { get; set; }
        public string Kostenstelle { get; set; }
        public string Erlöskonto { get; set; }
        public string Gegenkonto { get; set; }
        public string Aufwandskonto { get; set; }
        public Nullable<int> SkontoTage { get; set; }
        public Nullable<decimal> SkontoProzent { get; set; }
        public Nullable<int> NettoTage { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string Kennzeichen { get; set; }
        public string Buchungstext { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
