//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie
    {
        public int ID { get; set; }
        public string KategorieNr { get; set; }
        public string Kategorie1 { get; set; }
        public string Gegenkonto { get; set; }
        public string Bestandskonto { get; set; }
        public string Verbrauchskonto { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
