//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class KundenExterneMandantenSubunternehmer
    {
        public int ID { get; set; }
        public int ExternerMandant { get; set; }
        public int KundenNr { get; set; }
        public string DebitorNr { get; set; }
    }
}
