//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KundenExterneMandanten
    {
        public int ID { get; set; }
        public int KundenNr { get; set; }
        public string KreditorNr { get; set; }
        public string LieferantenNr { get; set; }
        public string Vorsteuerkonto { get; set; }
        public string AusgabepfadFibu { get; set; }
        public string AusgabepfadKore { get; set; }
        public string Verrechnungskonto { get; set; }
        public Nullable<System.DateTime> SyncDatum { get; set; }
        public string ConnectionString { get; set; }
    }
}
