//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunden
    {
        public int KundenNr { get; set; }
        public string DebitorNr { get; set; }
        public string Matchcode { get; set; }
        public string Firma { get; set; }
        public string KontaktVorname { get; set; }
        public string KontaktNachname { get; set; }
        public string FirmaOderAbteilung { get; set; }
        public string Rechnungsadresse { get; set; }
        public string Ort { get; set; }
        public string Bundesland { get; set; }
        public string Postleitzahl { get; set; }
        public string Land { get; set; }
        public string LandISO { get; set; }
        public string KontaktpersonPosition { get; set; }
        public string Telefonnummer { get; set; }
        public string Durchwahl { get; set; }
        public string Faxnummer { get; set; }
        public string EmailAdresse { get; set; }
        public string Anmerkungen { get; set; }
        public Nullable<decimal> RabattWA { get; set; }
        public Nullable<decimal> RabattSprit { get; set; }
        public Nullable<int> ZahlungszielID { get; set; }
        public Nullable<int> Preisgruppe { get; set; }
        public string Zahlungsziel { get; set; }
        public Nullable<int> PreisgruppeLohn { get; set; }
        public Nullable<decimal> RabattWALohn { get; set; }
        public string MwSt { get; set; }
        public string MwStReverseCharge { get; set; }
        public Nullable<decimal> AufschlagWA { get; set; }
        public Nullable<decimal> AufschlagWALohn { get; set; }
        public Nullable<decimal> AufschlagSprit { get; set; }
        public Nullable<bool> Sammelkonto { get; set; }
        public string UStIdNr { get; set; }
        public Nullable<bool> nichtsteuerbar { get; set; }
        public string Steuerbefreiung { get; set; }
        public string Kostenstelle { get; set; }
        public string SWIFT { get; set; }
        public string IBAN { get; set; }
        public string Kontonummer { get; set; }
        public Nullable<bool> ILV { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public Nullable<bool> LetzterZugriff_Export { get; set; }
    }
}
