//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lagerbewegungen
    {
        public int ID { get; set; }
        public Nullable<int> BewegArt { get; set; }
        public Nullable<int> ArtikelID { get; set; }
        public Nullable<int> LieferantenID { get; set; }
        public Nullable<int> WAID { get; set; }
        public Nullable<int> WAPosID { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public Nullable<decimal> E_Preis { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<bool> MR { get; set; }
        public string Lagerstelle { get; set; }
        public Nullable<bool> BW { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
