//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lizenzen
    {
        public int ID { get; set; }
        public string Lizenznummer1 { get; set; }
        public string Lizenznummer2 { get; set; }
        public string Lizenznummer3 { get; set; }
        public string Lizenznummer4 { get; set; }
        public string Lizenznummer5 { get; set; }
        public string Lizenznummer6 { get; set; }
        public string Lizenznummer7 { get; set; }
        public string Anfragenummer { get; set; }
        public string Aktivierungsnummer { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
