//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangelKopf
    {
        public int ID { get; set; }
        public int KFZNr { get; set; }
        public string MNr { get; set; }
        public string MBez { get; set; }
        public Nullable<decimal> Kilometerstand { get; set; }
        public string LauflEinheit { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<decimal> Zeitvorgabe { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<bool> Fremdauftrag { get; set; }
        public Nullable<bool> Exportiert { get; set; }
        public string Mangelart { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string Priorität { get; set; }
        public Nullable<System.DateTime> ErledigtDatum { get; set; }
        public Nullable<int> FahrerID { get; set; }
        public Nullable<bool> Gelesen { get; set; }
        public Nullable<System.DateTime> GelesenDatum { get; set; }
        public Nullable<int> GelesenPersonalID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
