//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mautbuchungen
    {
        public int ID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string Buchungsnummer { get; set; }
        public string Teilfahrt { get; set; }
        public string Kennzeichen { get; set; }
        public Nullable<System.DateTime> Startdatum { get; set; }
        public string StreckeAnfang { get; set; }
        public string StreckeVerlauf { get; set; }
        public string StreckeEnde { get; set; }
        public string Kostenstelle { get; set; }
        public Nullable<decimal> MautKilometer { get; set; }
        public string Version { get; set; }
        public string Achsklasse { get; set; }
        public string Schadstoffklasse { get; set; }
        public string Verfahren { get; set; }
        public Nullable<decimal> Mautbetrag { get; set; }
        public Nullable<int> FremdrechnungID { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public string FremdImportkurzbezeichnung { get; set; }
        public Nullable<System.DateTime> FremdImportdatum { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
