//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mautknoten
    {
        public int BAB { get; set; }
        public string K_NR1 { get; set; }
        public string K_TYP1 { get; set; }
        public string VON { get; set; }
        public string K_NR2 { get; set; }
        public string K_TYP2 { get; set; }
        public string NACH { get; set; }
        public decimal KM { get; set; }
        public string STATUS { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
