//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteraufträgeArtikel
    {
        public int ID { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> ArtikelID { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public string Lagerstelle { get; set; }
        public string Bemerkung { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
