//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameterdetail
    {
        public int ParameterdetailNr { get; set; }
        public int ParameterNr { get; set; }
        public string Wert1 { get; set; }
        public string Wert2 { get; set; }
        public string Wert3 { get; set; }
        public string Wert4 { get; set; }
        public string Wert5 { get; set; }
        public string Wert6 { get; set; }
        public string Wert7 { get; set; }
        public string Wert8 { get; set; }
        public string Wert9 { get; set; }
        public string Wert10 { get; set; }
        public string Wert11 { get; set; }
        public string Wert12 { get; set; }
        public string Wert13 { get; set; }
        public string Wert14 { get; set; }
        public string Wert15 { get; set; }
        public string Wert16 { get; set; }
        public string Wert17 { get; set; }
        public string Wert18 { get; set; }
        public string Wert19 { get; set; }
        public string Wert20 { get; set; }
        public string Wert21 { get; set; }
        public string Wert22 { get; set; }
        public string Wert23 { get; set; }
        public string Wert24 { get; set; }
        public string Wert25 { get; set; }
        public string Wert26 { get; set; }
        public string Wert27 { get; set; }
        public string Wert28 { get; set; }
        public string Wert29 { get; set; }
        public string Wert30 { get; set; }
        public string Wert31 { get; set; }
        public string Wert32 { get; set; }
        public string Wert33 { get; set; }
        public string Wert34 { get; set; }
        public string Wert35 { get; set; }
        public string Wert36 { get; set; }
        public string Wert37 { get; set; }
        public string Wert38 { get; set; }
        public string Wert39 { get; set; }
        public string Wert40 { get; set; }
        public string Wert41 { get; set; }
        public string Wert42 { get; set; }
        public string Wert43 { get; set; }
        public string Wert44 { get; set; }
        public string Wert45 { get; set; }
        public string Wert46 { get; set; }
        public string Wert47 { get; set; }
        public string Wert48 { get; set; }
        public string Wert49 { get; set; }
        public string Wert50 { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public string Memo3 { get; set; }
        public string Memo4 { get; set; }
        public string Memo5 { get; set; }
        public string Memo6 { get; set; }
        public string Memo7 { get; set; }
        public string Memo8 { get; set; }
        public string Memo9 { get; set; }
        public string Memo10 { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
