//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ID { get; set; }
        public string Firma { get; set; }
        public string Name { get; set; }
        public string Straße { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Telefon { get; set; }
        public string Telefax { get; set; }
        public string Ausgabepfad { get; set; }
        public string Importpfad { get; set; }
        public string Art { get; set; }
        public string Modus { get; set; }
        public string Sprit { get; set; }
        public Nullable<decimal> Absender { get; set; }
        public string Währung { get; set; }
        public string Modul1 { get; set; }
        public string Modul2 { get; set; }
        public string Modul3 { get; set; }
        public string Modul4 { get; set; }
        public string Modul5 { get; set; }
        public string Modul6 { get; set; }
        public string Modul7 { get; set; }
        public string Modul8 { get; set; }
        public string Modul9 { get; set; }
        public string Modul10 { get; set; }
        public string Parameter1 { get; set; }
        public Nullable<int> ParameterNr { get; set; }
        public Nullable<bool> Aktiviert { get; set; }
        public string Text { get; set; }
        public string AltteileMwSt { get; set; }
        public string Steuernummer { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
