//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personalfälligkeiten
    {
        public int ID { get; set; }
        public Nullable<int> Art { get; set; }
        public Nullable<int> PersonalNr { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<int> Intervall { get; set; }
        public Nullable<System.DateTime> Fälligkeit { get; set; }
        public Nullable<int> Vorlauf { get; set; }
        public Nullable<int> FahrerlaubnisklasseID { get; set; }
        public Nullable<int> BKFQID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
