//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalBenachrichtigungen
    {
        public int ID { get; set; }
        public int PersonalNr { get; set; }
        public int NachrichtArt { get; set; }
        public System.DateTime Zeitpunkt { get; set; }
        public string Betreff { get; set; }
        public string Nachricht { get; set; }
        public string Versandart { get; set; }
        public string Zieladresse { get; set; }
        public string Server { get; set; }
        public bool Erfolgreich { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
