//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalFührerscheine
    {
        public int ID { get; set; }
        public int PersonalNr { get; set; }
        public string Führerscheinnummer { get; set; }
        public Nullable<System.DateTime> Ausstellungsdatum { get; set; }
        public Nullable<System.DateTime> Ablaufdatum { get; set; }
        public string Ausstellungsbehörde { get; set; }
        public string Zusatzangaben { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<System.DateTime> Ausgabedatum { get; set; }
        public Nullable<bool> BerufskraftfahrerBus { get; set; }
        public Nullable<bool> BerufskraftfahrerLKW { get; set; }
        public Nullable<bool> Gültig { get; set; }
        public Nullable<bool> Eingezogen { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
