//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int ID { get; set; }
        public string Aktionsart { get; set; }
        public string FahrerNr { get; set; }
        public string FahrerName { get; set; }
        public string Personalkarte { get; set; }
        public string Reserve { get; set; }
        public decimal AWSatz { get; set; }
        public decimal SollAW { get; set; }
        public string Mengeneinheit { get; set; }
        public string Sozialversicherungsnummer { get; set; }
        public string Personalausweisnummer { get; set; }
        public string Versicherungsnummer { get; set; }
        public string Adresse { get; set; }
        public string Postleitzahl { get; set; }
        public string Ort { get; set; }
        public string TelefonPrivat { get; set; }
        public string TelefonBeruflich { get; set; }
        public string TelefonMobil { get; set; }
        public string EmailAdresse { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string Geburtsort { get; set; }
        public Nullable<System.DateTime> Eintritt { get; set; }
        public Nullable<System.DateTime> Austritt { get; set; }
        public Nullable<bool> Aktuell { get; set; }
        public string Führerscheinnummer { get; set; }
        public Nullable<System.DateTime> Führerscheindatum { get; set; }
        public string Führerscheinklassen { get; set; }
        public string Fahrerkartennummer { get; set; }
        public Nullable<System.DateTime> FahrerkarteDatum { get; set; }
        public string ADRNummer { get; set; }
        public Nullable<System.DateTime> ADRDatum { get; set; }
        public string NotfallKontaktperson { get; set; }
        public string NotfallTelefon { get; set; }
        public Nullable<decimal> Preisgruppe1 { get; set; }
        public Nullable<decimal> Preisgruppe2 { get; set; }
        public Nullable<decimal> Preisgruppe3 { get; set; }
        public Nullable<decimal> Preisgruppe4 { get; set; }
        public Nullable<decimal> Preisgruppe5 { get; set; }
        public Nullable<decimal> Preisgruppe6 { get; set; }
        public Nullable<decimal> Preisgruppe7 { get; set; }
        public Nullable<decimal> Preisgruppe8 { get; set; }
        public Nullable<decimal> Preisgruppe9 { get; set; }
        public Nullable<decimal> Preisgruppe10 { get; set; }
        public string Gegenkonto { get; set; }
        public string Bestandskonto { get; set; }
        public string Verbrauchskonto { get; set; }
        public string Kostenstelle { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<bool> Fahrer { get; set; }
        public Nullable<bool> Bearbeiter { get; set; }
        public Nullable<bool> Anmeldung { get; set; }
        public Nullable<bool> Superuser { get; set; }
        public string Passwort { get; set; }
        public Nullable<bool> WindowsAuthentifizierung { get; set; }
        public string Domäne { get; set; }
        public string Benutzer { get; set; }
        public string Miniaturbild { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
