//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produktart
    {
        public int ID { get; set; }
        public int Produktart1 { get; set; }
        public string Bezeichnung { get; set; }
        public string Mengeneinheit { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> CO2EmissionKg { get; set; }
        public string Gegenkonto { get; set; }
        public string Bestandskonto { get; set; }
        public string Verbrauchskonto { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
