//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechnungKopf
    {
        public int RechnungsNr { get; set; }
        public Nullable<int> KundenNr { get; set; }
        public Nullable<int> PersonalNr { get; set; }
        public Nullable<int> Liefer_Nr { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Rechnungsdatum { get; set; }
        public string Verkaufsberatername { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public string VersandAn { get; set; }
        public string VersandÜber { get; set; }
        public Nullable<decimal> Versandkosten { get; set; }
        public string Anmerkungen { get; set; }
        public Nullable<int> WAID { get; set; }
        public Nullable<int> SkontoTage { get; set; }
        public Nullable<decimal> SkontoProzent { get; set; }
        public Nullable<int> NettoTage { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<bool> Ausdruck { get; set; }
        public Nullable<bool> Exportiert { get; set; }
        public Nullable<bool> Gebucht { get; set; }
        public Nullable<bool> Storno { get; set; }
        public Nullable<bool> Sammelrechnung { get; set; }
        public string freieFirma { get; set; }
        public string freierKontaktNachname { get; set; }
        public string freieRechnungsadresse { get; set; }
        public string freiePostleitzahl { get; set; }
        public string freierOrt { get; set; }
        public string freiesLand { get; set; }
        public string freieUStIDNr { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public string ExterneNr { get; set; }
        public string Belegart { get; set; }
        public string Kostenstelle { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
