//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reifenbewegungen
    {
        public int ID { get; set; }
        public Nullable<int> BewegArt { get; set; }
        public Nullable<int> ReifenID { get; set; }
        public string Lagerstelle { get; set; }
        public string Lagerplatz { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public Nullable<decimal> Kilometerstand { get; set; }
        public Nullable<decimal> Profil { get; set; }
        public Nullable<int> Zustand { get; set; }
        public Nullable<decimal> Luftdruck { get; set; }
        public Nullable<int> Fahrgestellposition { get; set; }
        public Nullable<decimal> bEK { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
