//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reifen
    {
        public int ID { get; set; }
        public string ReifenNr { get; set; }
        public string Reifenfelge { get; set; }
        public string Reifengrösse { get; set; }
        public string Reifenhersteller { get; set; }
        public string Reifentyp { get; set; }
        public string DOTNr { get; set; }
        public Nullable<decimal> Laufleistung { get; set; }
        public Nullable<int> LieferantenNr { get; set; }
        public string Bemerkung { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
