//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spritbuchungen
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public string FahrerNr { get; set; }
        public Nullable<System.DateTime> Tankdatum { get; set; }
        public string TerminalNr { get; set; }
        public Nullable<decimal> Kilometerstand { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public Nullable<decimal> EPreis { get; set; }
        public Nullable<decimal> Preis { get; set; }
        public Nullable<int> FremdrechnungID { get; set; }
        public string MwSt { get; set; }
        public Nullable<decimal> MwStProzent { get; set; }
        public Nullable<int> Tankart { get; set; }
        public Nullable<decimal> AggrStd { get; set; }
        public Nullable<bool> Gelöscht { get; set; }
        public Nullable<System.DateTime> Löschdatum { get; set; }
        public Nullable<int> Produktart { get; set; }
        public string FremdImportkurzbezeichnung { get; set; }
        public Nullable<System.DateTime> FremdImportdatum { get; set; }
        public Nullable<int> SyncID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
