//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandorteFahrzeugZuordnungErweitert
    {
        public int ID { get; set; }
        public int KFZNr { get; set; }
        public string Standort { get; set; }
        public System.DateTime ZeitraumVon { get; set; }
        public System.DateTime ZeitraumBis { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public string Parkplatz { get; set; }
    }
}
