//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standorte
    {
        public int ID { get; set; }
        public string Standort { get; set; }
        public string Bezeichnung { get; set; }
        public string Kostenstelle { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public string Lieferantenname { get; set; }
        public string Kontaktperson { get; set; }
        public string KontaktpersonPosition { get; set; }
        public string Adresse { get; set; }
        public string Ort { get; set; }
        public string Postleitzahl { get; set; }
        public string Bundesland { get; set; }
        public string Land { get; set; }
        public string LandISO { get; set; }
        public string Telefonnummer { get; set; }
        public string Faxnummer { get; set; }
        public string EmailAdresse { get; set; }
        public string Anmerkungen { get; set; }
        public string KreditorNr { get; set; }
        public string UnsereKundenNr { get; set; }
    }
}
