//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Steuersätze
    {
        public int ID { get; set; }
        public string Matchcode { get; set; }
        public string Kurzbezeichnung { get; set; }
        public Nullable<decimal> MwSt { get; set; }
        public string Gegenkonto { get; set; }
        public string GegenkontoTA { get; set; }
        public string GegenkontoMR { get; set; }
        public string GegenkontoMA { get; set; }
        public string GegenkontoAltteile { get; set; }
        public string VstGegenkonto { get; set; }
        public string VstGegenkontoTA { get; set; }
        public string VstGegenkontoMR { get; set; }
        public string VstGegenkontoMA { get; set; }
        public string VstGegenkontoAltteile { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
