//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminKopf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerminKopf()
        {
            this.TerminAbrechnungs = new HashSet<TerminAbrechnung>();
            this.TerminDokumentes = new HashSet<TerminDokumente>();
            this.TerminFreifelders = new HashSet<TerminFreifelder>();
        }
    
        public int ID { get; set; }
        public string TerminGUID { get; set; }
        public string Kurzbezeichnung { get; set; }
        public System.DateTime TerminVon { get; set; }
        public System.DateTime TerminBis { get; set; }
        public string Serientyp { get; set; }
        public Nullable<int> HauptTerminID { get; set; }
        public string Ort { get; set; }
        public Nullable<int> AnzeigenAls { get; set; }
        public string KategorieNr { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public Nullable<int> AnhängerNr { get; set; }
        public Nullable<int> StartKilometerstand { get; set; }
        public Nullable<int> EndeKilometerstand { get; set; }
        public Nullable<int> PersonalNr { get; set; }
        public Nullable<int> KundenNr { get; set; }
        public Nullable<int> AbrechnungVorlageID { get; set; }
        public string Kostenstelle { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminAbrechnung> TerminAbrechnungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminDokumente> TerminDokumentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminFreifelder> TerminFreifelders { get; set; }
        public virtual TerminKategorien TerminKategorien { get; set; }
    }
}
