//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminAbrechnung
    {
        public int ID { get; set; }
        public int TerminID { get; set; }
        public int Abrechnungsart { get; set; }
        public Nullable<int> Kilometer { get; set; }
        public Nullable<decimal> KilometerPreis { get; set; }
        public Nullable<decimal> MehrKilometerPreis { get; set; }
        public Nullable<decimal> InklusivKilometer { get; set; }
        public Nullable<decimal> PauschalPreis { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    
        public virtual TerminKopf TerminKopf { get; set; }
    }
}
