//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfallKopf
    {
        public int ID { get; set; }
        public int KFZNr { get; set; }
        public string Unfallart { get; set; }
        public string Bezeichnung { get; set; }
        public int FahrerID { get; set; }
        public string Beschreibung { get; set; }
        public System.DateTime Unfalldatum { get; set; }
        public string Unfallort { get; set; }
        public string Land { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string Eigenschaden { get; set; }
        public string Geschädigter { get; set; }
        public string Adresse { get; set; }
        public string Ort { get; set; }
        public string Postleitzahl { get; set; }
        public string Fahrzeug { get; set; }
        public string Kennzeichen { get; set; }
        public string VersicherungsName { get; set; }
        public string VersicherungsNr { get; set; }
        public string Telefonnummer { get; set; }
        public string Fremdschaden { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<System.DateTime> ErledigtDatum { get; set; }
        public Nullable<bool> Polizeibericht { get; set; }
        public string Polizeiberichttext { get; set; }
        public Nullable<bool> Stillstand { get; set; }
        public string Stillstandtext { get; set; }
        public Nullable<decimal> SummeEigenschaden { get; set; }
        public Nullable<decimal> SummeFremdschaden { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
