//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WerbungKopf
    {
        public int ID { get; set; }
        public int KFZNr { get; set; }
        public string Werbefläche { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<decimal> EPreis { get; set; }
        public Nullable<System.DateTime> vonDatum { get; set; }
        public Nullable<System.DateTime> bisDatum { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> LieferantenID { get; set; }
        public Nullable<System.DateTime> Wiedervorlage { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
