//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WerkstattauftragKopf
    {
        public int ID { get; set; }
        public Nullable<int> KFZNr { get; set; }
        public Nullable<int> KundenNr { get; set; }
        public string WANr { get; set; }
        public string WABez { get; set; }
        public Nullable<decimal> Kilometerstand { get; set; }
        public string LauflEinheit { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<decimal> Zeitvorgabe { get; set; }
        public Nullable<bool> Erledigt { get; set; }
        public Nullable<System.DateTime> ErledigtBis { get; set; }
        public Nullable<bool> Fremdauftrag { get; set; }
        public Nullable<bool> Exportiert { get; set; }
        public Nullable<bool> ExportiertInterface { get; set; }
        public string Auftragsart { get; set; }
        public string Status { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<System.DateTime> TerminVon { get; set; }
        public Nullable<System.DateTime> TerminBis { get; set; }
        public Nullable<bool> Gebucht { get; set; }
        public string TerminGUID { get; set; }
        public string freiesKennzeichen { get; set; }
        public Nullable<System.DateTime> freieZulassung { get; set; }
        public string freieFahrgestellNr { get; set; }
        public string Standort { get; set; }
        public string Priorität { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
        public Nullable<int> RechnungKopfKundenNr { get; set; }
    }
}
