//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCustomControlLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahlungsziele
    {
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<int> SkontoTage { get; set; }
        public Nullable<int> NettoTage { get; set; }
        public Nullable<decimal> SkontoProzent { get; set; }
        public string Matchcode { get; set; }
        public string Sprachschlüssel { get; set; }
        public string Bankkonto { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
