//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHWpfViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zeiterfassung
    {
        public int ID { get; set; }
        public int PersonalID { get; set; }
        public string PersonalName { get; set; }
        public int WAID { get; set; }
        public Nullable<System.DateTime> Beginn { get; set; }
        public Nullable<System.DateTime> Ende { get; set; }
        public Nullable<decimal> IndustrieStd { get; set; }
        public string MDE_MAC { get; set; }
        public Nullable<int> MDE_ID { get; set; }
        public string GeräteID { get; set; }
        public string LetzterZugriff_Benutzer { get; set; }
        public Nullable<System.DateTime> LetzterZugriff_Datum { get; set; }
    }
}
